### ISSUE TITLE
blackarch-menus

### ISSUE THREAD

**Issue by visious25** [BlackArch/blackarch-menus#2]
- [ ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Bug description

blackarch-menus version 10.5244eea-1 it doesn't appears in xfce menu.

**Comment by visious25** [comment]
I don't  want to see all tools. It doesn't show up blackarch-menus at all. Yes nmap working well.

**Comment by Edu4rdSHL** [comment]
Please send screenshots of your problem and explain:

- What are you trying to do.
- What is happening. 
- What do you expect. 

Actually it's hard to guess what's your real problem.

**Comment by visious25** [comment]
I was expecting blackarch-menus empty,

![blackarch-menus-missing](https://user-images.githubusercontent.com/81131095/112025416-cf2c8780-8b3d-11eb-93f5-564bdd73aa8c.png)

**Comment by Edu4rdSHL** [comment]
Please give the output for `pacman -Qi blackarch-menus`

**Comment by visious25** [comment]
Name            : blackarch-menus
Version         : 10.5244eea-1
Description     : BlackArch specific XDG-compliant menu.
Architecture    : any
URL             : https://github.com/BlackArch/blackarch-menus
Licenses        : custom:unknown
Groups          : blackarch-config
Provides        : None
Depends On      : xdg-utils
Optional Deps   : None
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 20.93 KiB
Packager        : Levon Kayan <noptrix@nullsecurity.net>
Build Date      : Sat 06 Mar 2021 03:15:17 AM EET
Install Date    : Sun 07 Mar 2021 02:12:59 PM EET
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature

**Comment by Edu4rdSHL** [comment]
1. Have you logged out/logged in after the installation?
2. `nmap` is not in the `blackarch` group, so no entry is created. Can you install another tool like `airgeddon` and see if the entries are created?

**Comment by visious25** [comment]
I have installed airgeddon and restart my pc. The blackarch-menus now appears in xfce menu and show up airgeddon, aircrack-ng.

**Comment by visious25** [comment]
I have installed airgeddon and restart my pc. The blackarch-menus now appears in xfce menu and show up airgeddon, aircrack-ng.

**Comment by visious25** [comment]
nmap has two repositories, 1 for archlinux -> extra and 1 for blackarch must be in the group blackarch ->  blackarch-scanner.

The output of: pacman -Si nmap 

Repository      : extra
Name            : nmap
Version         : 7.91-1
Description     : Utility for network discovery and security auditing
Architecture    : x86_64
URL             : https://nmap.org/
Licenses        : GPL2
Groups          : None
Provides        : None
Depends On      : glibc  pcre  openssl  lua53  libpcap  libssh2
                  libssh2.so=1-64  zlib  gcc-libs
Optional Deps   : None
Conflicts With  : None
Replaces        : None
Download Size   : 5.41 MiB
Installed Size  : 24.00 MiB
Packager        : Levente Polyak <anthraxx@archlinux.org>
Build Date      : Wed 11 Nov 2020 12:07:21 AM EET
Validated By    : MD5 Sum  SHA-256 Sum  Signature

Repository      : blackarch
Name            : nmap
Version         : 7.91-1
Description     : Utility for network discovery and security auditing
Architecture    : x86_64
URL             : https://nmap.org/
Licenses        : GPL2
Groups          : blackarch  blackarch-scanner
Provides        : None
Depends On      : glibc  pcre  openssl  lua53  libpcap  libssh2
                  libssh2.so=1-64  zlib  gcc-libs
Optional Deps   : None
Conflicts With  : None
Replaces        : None
Download Size   : 5.41 MiB
Installed Size  : 24.00 MiB
Packager        : Levente Polyak <anthraxx@archlinux.org>
Build Date      : Wed 11 Nov 2020 12:07:21 AM EET
Validated By    : MD5 Sum  SHA-256 Sum  Signature

**Comment by Edu4rdSHL** [comment]
Uninstall nmap and reinstall it, my guess is that you have installed nmap then blackarch-menus, the pacman hook that creates the menu entries is triggered when a package is installed/uninstalled, that's why the menu entry is not yet created for nmap. Once you uninstall and install it again, it should appear in the menu.

**Comment by visious25** [comment]
Yes, I uninstalled/installed nmap appears in the menu.
I couldn't downgrade blackarch-menus to show you exactly with a new picture what I mean.

Best Regards

**Comment by Edu4rdSHL** [comment]
Great, can I consideer this issue as solved?

**Comment by visious25** [comment]
Yes sure.
